### Vendored plugins and installed-tool integration (rich class only)
#
# Plain `source` of files under ../plugins -- no plugin manager. See
# plugins/VENDORED.md for provenance.

plugins_dir=${XDG_CONFIG_HOME:-$HOME/.config}/zsh/plugins

# Suggestions from history, shown inline in grey.
[[ -r $plugins_dir/zsh-autosuggestions.zsh ]] && source $plugins_dir/zsh-autosuggestions.zsh

# `z <partial>` jumps to a frecently-used directory. The _zshz completion lives
# in ../functions, which 15-functions.zsh puts on $fpath.
[[ -r $plugins_dir/zsh-z.zsh ]] && source $plugins_dir/zsh-z.zsh

# fzf key bindings (Ctrl+R history, Ctrl+T files, Alt+C cd). Since fzf 0.48
# this is generated by fzf itself, so no separate integration snippet is
# vendored.
if (( $+commands[fzf] )); then
    source <(fzf --zsh)

    # fzf binds ^I to a shim that inspects the word for its ** trigger and
    # otherwise re-invokes the previous widget through a nested zle call --
    # one moving part too many under the autosuggestion/highlighting
    # wrappers, and it glitched mid-word completion in the field. Keep TAB
    # pure zsh; fzf gets its own key instead: Shift-TAB fuzzy-completes the
    # word before the cursor (files and dirs; hosts after ssh, PIDs after
    # kill), no trigger characters involved.
    bindkey '^I' expand-or-complete-prefix
    _fzf_shift_tab() { FZF_COMPLETION_TRIGGER='' fzf-completion; }
    zle -N _fzf_shift_tab
    bindkey '^[[Z' _fzf_shift_tab
fi

unset plugins_dir
