### Vendored plugins and installed-tool integration (rich class only)
#
# Plain `source` of files under ../plugins -- no plugin manager. See
# plugins/VENDORED.md for provenance.

plugins_dir=${XDG_CONFIG_HOME:-$HOME/.config}/zsh/plugins

# Suggestions from history, shown inline in grey.
[[ -r $plugins_dir/zsh-autosuggestions.zsh ]] && source $plugins_dir/zsh-autosuggestions.zsh

# `z <partial>` jumps to a frecently-used directory. The _zshz completion lives
# in ../functions, which 15-functions.zsh puts on $fpath.
[[ -r $plugins_dir/zsh-z.zsh ]] && source $plugins_dir/zsh-z.zsh

# fzf key bindings (Ctrl+R history, Ctrl+T files, Alt+C cd). Since fzf 0.48
# this is generated by fzf itself, so no separate integration snippet is
# vendored.
if (( $+commands[fzf] )); then
    # fzf captures whatever ^I was bound to into $fzf_default_completion and
    # its fzf-completion widget delegates there unless the word ends in the
    # ** trigger. So plain TAB stays expand-or-complete-prefix (bound in
    # 50-keybindings.zsh, sourced before this), and `path/**<TAB>` opens the
    # fuzzy picker, on purpose.
    source <(fzf --zsh)
fi

unset plugins_dir
